Change strict mode and parallel execution parameters.
- To bash strict mode, add trap that reports error message.
- In first parallel CSV concatenation, limit number of CSV arguments for each
  concurrent job to 5000.
- In second parallel CSV concatenation, limit number of CSV arguments to two.

diff --git a/cat_csv b/cat_csv
--- a/cat_csv
+++ b/cat_csv
@@ -1,7 +1,6 @@
-#!/bin/bash
-
+#!/usr/bin/env bash
 set -euo pipefail
-IFS=$'\n\t'
+trap 's=$?; echo >&2 "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR
 
 set -o xtrace
 
@@ -11,18 +10,36 @@ trap "rm -fr $top_directory_name" EXIT
 working_directory_name=$(mktemp --tmpdir=$top_directory_name --directory)
 
 temp_file_names=$(
-  parallel --files --keep-order --tmpdir $working_directory_name --verbose --xargs xsv cat rows
+  parallel \
+    --files \
+    --joblog cat_csv.log \
+    --keep-order \
+    --max-args 5000 \
+    --progress \
+    --tmpdir $working_directory_name \
+    --verbose \
+    xsv cat rows
 )
 
 temp_file_names_count=$(echo "$temp_file_names" | wc -l)
 
 while [[ $temp_file_names_count -gt 1 ]]
 do
+  old_working_directory_name=$working_directory_name
   working_directory_name=$(mktemp --tmpdir=$top_directory_name --directory)
   temp_file_names=$(echo "$temp_file_names" |
-    parallel --files --keep-order --tempdir $working_directory_name --verbose --xargs xsv cat rows 
+    parallel \
+      --files \
+      --keep-order \
+      --line-buffer \
+      --max-args 2 \
+      --progress \
+      --tempdir $working_directory_name \
+      --verbose \
+      xsv cat rows
   )
   temp_file_names_count=$(echo "$temp_file_names" | wc -l)
+  rm -fr $old_working_directory_name
 done
 
 cat $working_directory_name/* /dev/null
